name: solar test
on:
    push:
        branches: 
            - main
            - 'feature/*'
env:
    MONGO_URI: ${{ vars.MONGO_URI }}
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                nodejs_v: [18, 20]
                exclude:
                    - os: macos-latest
                      nodejs_v: 20
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Install nodejs ${{ matrix.nodejs_v }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.nodejs_v }}
            - name: Install Dependency
              run: npm install
            - name: Run unit test
              run: npm test
            - name: Archive test result
              uses: actions/upload-artifact@v4
              with:
                name: mocha-test-result-${{ matrix.os }}-${{ matrix.nodejs_v }}
                path: test-results.xml
                retention-days: 3
